### ISSUE TITLE
Discover tool seems to not be discovering all values

### ISSUE THREAD

**Issue by WhatDoor** [oracle/weblogic-deploy-tooling#1385] opened 2023-02-09 19:15 UTC
Hi, when running the discover tool i get these two results from two of our environments (extract)

`
BIT

CoherenceClusterSystemResource:

        defaultCoherenceCluster:

            CoherenceResource:

                CoherenceClusterParams:

                    ClusteringMode: unicast

                    Transport: tmb

                    TimeToLive: 4

                    UnicastListenPort: 9991

                    ClusterListenPort: 9991

                    CoherenceClusterWellKnownAddress:

                        WKA1:

                            ListenAddress: GDFMW000026

                        WKA2:

                            ListenAddress: GDFMW000027

                        WKA3:

                            ListenAddress: GDFMW000028

                        WKA4:

                            ListenAddress: GDFMW000030

 

SPA

CoherenceClusterSystemResource:

                defaultCoherenceCluster:

                                Target: osb_server01,soa_server01,ess_server01,soa_server02,soa_server03,soa_server04,osb_server02,osb_server03,osb_server04,wsm_server01,wsm_server02,wsm_server03,wsm_server04,ess_server02,ess_server03,ess_server04

                                CoherenceResource:

                                                CoherenceClusterParams:

                                                                UnicastListenPort: 9991

                                                                ClusterListenPort: 9991

                                                                CoherenceClusterWellKnownAddress:

                                                                                WKA1:

                                                                                                ListenAddress: GPFMW000007

                                                                                WKA2:

                                                                                                ListenAddress: GPFMW000008

                                                                                WKA3:

                                                                                                ListenAddress: GPFMW000009

                                                                                WKA4:

                                                                                                ListenAddress: GPFMW000010
`

The values such as 
ClusteringMode: unicast
Transport: tmb
TimeToLive: 4

are configured the same in both, but dont seem to be captured in the resulting SPA model.

**Comment by CarolynRountree** [comment] 2023-02-09 20:30
Please provide the config.xml from both of the domains.

**Comment by WhatDoor** [comment] 2023-02-10 05:53
[bit_config.txt](https://github.com/oracle/weblogic-deploy-tooling/files/10704101/bit_config.txt)
[spa_config.txt](https://github.com/oracle/weblogic-deploy-tooling/files/10704102/spa_config.txt)

Ive renamed the files to txt so github will accept them.

**Comment by robertpatrick** [comment] 2023-02-13 21:54
@WhatDoor discoverDomain does not write attributes whose values are "not set" (e.g., not set to a value that is different than the default value).  It appears that you were using discoverDomain in online mode where the default value for `ClusteringMode` is `unicast`:

https://github.com/oracle/weblogic-deploy-tooling/blob/main/core/src/main/resources/oracle/weblogic/deploy/aliases/category_modules/CoherenceClusterSystemResource.json#L176

**Comment by WhatDoor** [comment] 2023-02-13 22:25
I see, thanks for that clarification Robert. 

So I ran the discovery tool on BIT in offline mode, where the default is blank resulting in those values being written. And then I ran the discovery tool in SPA in online mode, where the values matched the default. 

This results in the output I'm seeing. Is my understanding correct?

**Comment by WhatDoor** [comment] 2023-02-13 23:18
Hi, 

I just ran the discovery again on the SPA environment in offline mode and it's still not showing those values. 

Here is the command I ran
`/u01/app/oracle/product/fmw1221//oracle_common/common/bin/wlst.sh /home/oracle/weblogic-deploy/lib/python/discover.py -oracle_home /u01/app/oracle/product/fmw1221/ -domain_home /u01/app/oracle/admin/ent_soa_spa_domain/aserver/ent_soa_spa_domain/ -archive_file /home/oracle/discoveredspa.zip -model_file /home/oracle/discoverspa.yaml -variable_file /home/oracle/discoveredspa.props`

**Comment by CarolynRountree** [comment] 2023-02-14 00:18
Could you zip up and provide the config directory for spa

**Comment by WhatDoor** [comment] 2023-02-14 02:26
Can you specify the files you want to see? So I can check them before sharing them.

**Comment by robertpatrick** [comment] 2023-02-14 12:21
@WhatDoor yes, your understanding is correct.  It is very unlikely that discoverDomain is not working in terms of which attributes are being written to the model.  What version of WDT are you using?

Try reading the domain with WLST offline and see what values those attributes have?

**Comment by robertpatrick** [comment] 2023-02-14 12:29
@WhatDoor when trying to replicate issues, it is not uncommon for us to ask for the entire $DOMAIN_HOME/config directory so that we can simulate your domain.  You should feel free to ask to send it directly to the person asking rather than posting it but rest assured, we treat your data with the utmost consideration for maintaining privacy and, without the domain encryption keys, we cannot read encrypted database passwords and such.

I am still unsure of the purpose of this issue.  Is there something you are trying to accomplish that isn't working or is this just you trying to understand the behavior of the tool?

**Comment by CarolynRountree** [comment] 2023-02-14 19:11
carolyn.rountree@oracle.com

**Comment by robertpatrick** [comment] 2023-02-14 22:30
Offline discovered model:

```
resources:
    CoherenceClusterSystemResource:
        Coherence-0:
            CoherenceResource:
                CoherenceClusterParams:
                    ClusteringMode: unicast
                    Transport: udp
                    TimeToLive: 4
                    ClusterListenPort: 7574
```

online discovered model:

```
esources:
    CoherenceClusterSystemResource:
        Coherence-0:
            Target: Cluster-0-1,Cluster-0-2
            CoherenceResource:
                CoherenceClusterParams:
                    ClusterListenPort: 7574
```

I am unable to reproduce your issue.  Closing as works as designed.  Feel free to reopen the issue if you have a reproducible test case.

**Closed by robertpatrick** 2023-02-14 22:30 UTC
Labels: awaiting user response, works as designed
