### ISSUE TITLE
create domain performance

### ISSUE THREAD

**Issue by dborysenko** [oracle/weblogic-deploy-tooling#772] opened 2020-10-28 20:02 UTC
Hi Team,
We use WDT to create large domains >100 managed servers. And we've noticed "create_placeholder_named_elements" step takes longer and longer throughout domain creation:

```
####<Oct 28, 2020 6:11:19 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server osb_server2>
####<Oct 28, 2020 6:11:19 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server osb_server3>
####<Oct 28, 2020 6:11:21 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server osb_server4>
####<Oct 28, 2020 6:11:22 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server osb_server5>
####<Oct 28, 2020 6:11:24 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server osb_server6>
####<Oct 28, 2020 6:11:27 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server osb_server7>
####<Oct 28, 2020 6:11:29 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server osb_server8>
####<Oct 28, 2020 6:11:33 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server osb_server9>
####<Oct 28, 2020 6:11:37 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server osb_server10>
####<Oct 28, 2020 6:11:44 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server web_server1>
####<Oct 28, 2020 6:11:52 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server web_server2>
####<Oct 28, 2020 6:11:59 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server web_server3>
####<Oct 28, 2020 6:12:08 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server web_server4>
####<Oct 28, 2020 6:12:19 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server web_server5>
```
Above you can see each placeholder creation takes few seconds to complete. But when it comes to create placeholder for, as example, web_server**70**, it takes more than 3 minutes:
```
####<Oct 28, 2020 7:33:54 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server web_server68>
####<Oct 28, 2020 7:37:08 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server web_server69>
####<Oct 28, 2020 7:40:20 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server web_server70>
####<Oct 28, 2020 7:43:41 PM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server web_server71>
```
Another observation is that during this phase of domain creation, JVM process consumes 100% of a single CPU core.
Is there a way to speedup this phase? It takes more than 5hours to create domain with 100 managed servers.

PS: dynamic clusters are not an option for us as it is not supported in JRF domains (at least weblogic operator documentation says so).

**Comment by dborysenko** [comment] 2020-10-28 20:31
Snippet of domain template
```
domainInfo:
  AdminUserName: '@@FILE:/weblogic-operator/secrets/username@@'
  AdminPassword: '@@FILE:/weblogic-operator/secrets/password@@'
  ServerStartMode: prod
  RCUDbInfo:
    rcu_prefix: '@@PROP:rcuSchemaPrefix@@'
    rcu_schema_password: '@@PROP:rcuSchemaPassword@@'
    rcu_db_user: '@@PROP:rcuAdminUser@@'
    rcu_admin_password: '@@PROP:rcuAdminPassword@@'
    rcu_db_conn_string: '@@PROP:rcuDatabaseURL@@'
    rcu_variables: "SOA_PROFILE_TYPE=LARGE,HEALTHCARE_INTEGRATION=NO"
  ServerGroupTargetingLimits:
    'OSB-MGD-SVRS-COMBINED': [ osb_cluster_1]
  WLSRoles:
    Admin:
      UpdateMode: append
      Expression: "?weblogic.entitlement.rules.AdministrativeGroup(myadmingroup)"
    IntegrationAdmin:
      UpdateMode: append
      Expression: "?weblogic.entitlement.rules.AdministrativeGroup(myadmingroup)"
topology:
  AdminServerName: AdminServer
  Name: '@@PROP:domainUID@@'
  ProductionModeEnabled: true
  Cluster:
    osb_cluster_1:
    web_cluster_1:
    web_cluster_2:
    web_cluster_3:
    web_cluster_4:
    web_cluster_5:
    web_cluster_6:
    web_cluster_7:
    web_cluster_8:
    web_cluster_9:
    web_cluster_10:
  Server:
    AdminServer:
      KeyStores: CustomIdentityAndCustomTrust
      CustomIdentityKeyStoreType: jks
      CustomIdentityKeyStoreFileName: wlsdeploy/servers/AdminServer/DemoIdentity.jks
      CustomIdentityKeyStorePassPhraseEncrypted: '{AES}mybase64pwd'
      CustomTrustKeyStorePassPhraseEncrypted: '{AES}mybase64pwd'
      CustomTrustKeyStoreType: jks
      CustomTrustKeyStoreFileName: wlsdeploy/servers/AdminServer/myTrust.jks
      ListenPort: 7001
      SSL:
        Enabled: false
        ListenPort: 7002
        HostnameVerificationIgnored: true
        ServerPrivateKeyPassPhraseEncrypted: '{AES}mykey'
        JSSEEnabled: true
        ServerPrivateKeyAlias: DemoIdentity
    web_server1:
      Cluster: web_cluster_1
      NumOfRetriesBeforeMsiMode: 0
      RetryIntervalBeforeMsiMode: 1
      JTAMigratableTarget:
        Cluster: web_cluster_1
      KeyStores: CustomIdentityAndCustomTrust
      CustomIdentityKeyStoreType: jks
      CustomIdentityKeyStoreFileName: wlsdeploy/servers/web_server1/DemoIdentity.jks
      CustomIdentityKeyStorePassPhraseEncrypted: '{AES}mybase64pwd'
      CustomTrustKeyStorePassPhraseEncrypted: '{AES}mybase64pwd'
      CustomTrustKeyStoreType: jks
      CustomTrustKeyStoreFileName: wlsdeploy/servers/web_server1/myTrust.jks
      ListenPort: 8301

[skipped]

    web_server71:
      Cluster: web_cluster_8
      NumOfRetriesBeforeMsiMode: 0
      RetryIntervalBeforeMsiMode: 1
      JTAMigratableTarget:
        Cluster: web_cluster_8
      KeyStores: CustomIdentityAndCustomTrust
      CustomIdentityKeyStoreType: jks
      CustomIdentityKeyStoreFileName: wlsdeploy/servers/web_server1/DemoIdentity.jks
      CustomIdentityKeyStorePassPhraseEncrypted: '{AES}mybase64pwd'
      CustomTrustKeyStorePassPhraseEncrypted: '{AES}mybase64pwd'
      CustomTrustKeyStoreType: jks
      CustomTrustKeyStoreFileName: wlsdeploy/servers/web_server1/myTrust.jks
      ListenPort: 8301

[skipped]
```

**Comment by CarolynRountree** [comment] 2020-10-30 21:29
Investigating

**Comment by CarolynRountree** [comment] 2020-11-02 19:53
Could you run a create domain with the simplified yaml (attached) please? I am hoping to separate whether this is an environment or something to do with the complex yaml. The method in question is very simple. It looks up the existing clusters and creates the cluster. It does not do anything with the keystore file or other attributes.

If this runs a long time, can you tell me more about your environment and also whether you override the memory settings for the create.

If this test does not run a long time, would you be able to give me your entire yaml, or at least the SecurityConfiguration section?

**Comment by CarolynRountree** [comment] 2020-11-02 19:57
[d100.zip](https://github.com/oracle/weblogic-deploy-tooling/files/5477678/d100.zip)

**Comment by dborysenko** [comment] 2020-11-05 03:01
Hey @CarolynRountree 
Using your model file WDT creates domain blazing fast. Please see below snippets from log file. 
Now the question is how to speed up the tool on more real life domain models?

```
####<Nov 5, 2020 2:51:00 AM> <INFO> <WebLogicDeployToolingVersion> <logVersionInfo> <WLSDPLY-01750> <The WebLogic Deploy Tooling createDomain version is 1.9.6:master.2c18938:Oct 19, 2020 21:56 UTC>
####<Nov 5, 2020 2:51:00 AM> <INFO> <PyReflectedFunction> <__call__> <WLSDPLY-12402> <createDomain was called with the -run_rcu command-line switch but the specified domain type WLS defines no RCU schemas so RCU will not be run>
Enter the encryption passphrase used to encrypt the model passwords: ####<Nov 5, 2020 2:51:04 AM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20017> <No filter configuration file /shared/wdt-as-msp01-domain3/weblogic-deploy/lib/model_filters.json>
####<Nov 5, 2020 2:51:04 AM> <INFO> <filter_helper> <apply_filters> <WLSDPLY-20016> <No filters of type create found in filter configuration file /shared/wdt-as-msp01-domain3/weblogic-deploy/lib/model_filters.json>
####<Nov 5, 2020 2:51:04 AM> <INFO> <DomainCreator> <__create_domain> <WLSDPLY-12203> <Creating domain of type WLS>
####<Nov 5, 2020 2:51:04 AM> <INFO> <DomainCreator> <__create_base_domain_with_select_template> <WLSDPLY-12210> <Selecting base template named Basic WebLogic Server Domain>
####<Nov 5, 2020 2:51:11 AM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12212> <Loading selected templates>
####<Nov 5, 2020 2:51:17 AM> <INFO> <DomainCreator> <__set_domain_name> <WLSDPLY-12227> <Changing domain name from base_domain to eu_domain>
####<Nov 5, 2020 2:51:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12100> <Creating Cluster with the name c2>
####<Nov 5, 2020 2:51:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12100> <Creating Cluster with the name c3>
####<Nov 5, 2020 2:51:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12100> <Creating Cluster with the name c4>
####<Nov 5, 2020 2:51:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12100> <Creating Cluster with the name c5>
####<Nov 5, 2020 2:51:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12100> <Creating Cluster with the name c6>
####<Nov 5, 2020 2:51:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12100> <Creating Cluster with the name c7>
####<Nov 5, 2020 2:51:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12100> <Creating Cluster with the name c8>
####<Nov 5, 2020 2:51:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12100> <Creating Cluster with the name c9>
####<Nov 5, 2020 2:51:18 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12100> <Creating Cluster with the name c10>
####<Nov 5, 2020 2:51:18 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms1>
####<Nov 5, 2020 2:51:19 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms2>
####<Nov 5, 2020 2:51:19 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms101>
####<Nov 5, 2020 2:51:19 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms102>
####<Nov 5, 2020 2:51:19 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms3>
####<Nov 5, 2020 2:51:20 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms4>
####<Nov 5, 2020 2:51:20 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms5>
####<Nov 5, 2020 2:51:20 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms6>
####<Nov 5, 2020 2:51:20 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms7>
####<Nov 5, 2020 2:51:20 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms8>
####<Nov 5, 2020 2:51:20 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms9>
####<Nov 5, 2020 2:51:21 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms10>
####<Nov 5, 2020 2:51:21 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms11>
####<Nov 5, 2020 2:51:21 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms12>

[ skipped ]

####<Nov 5, 2020 2:51:54 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms98>
####<Nov 5, 2020 2:51:55 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms99>
####<Nov 5, 2020 2:51:55 AM> <INFO> <TopologyHelper> <create_placeholder_named_elements> <WLSDPLY-19403> <Creating placeholder for Server ms100>
####<Nov 5, 2020 2:51:56 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name AdminServer>
####<Nov 5, 2020 2:51:56 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name ms1>
####<Nov 5, 2020 2:51:56 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name ms2>

[ skipped ]

####<Nov 5, 2020 2:52:21 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name ms99>
####<Nov 5, 2020 2:52:21 AM> <INFO> <Creator> <_create_named_mbeans> <WLSDPLY-12101> <Updating Server with the name ms100>
####<Nov 5, 2020 2:52:21 AM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12205> <Writing base domain eu_domain to directory /shared/domains/as-msp01-domain3>
####<Nov 5, 2020 2:52:30 AM> <INFO> <DomainCreator> <__extend_domain_with_select_template> <WLSDPLY-12206> <Closing templates for domain eu_domain>
####<Nov 5, 2020 2:52:32 AM> <INFO> <LibraryHelper> <install_domain_libraries> <WLSDPLY-12213> <The model did not specify any domain libraries to install>
####<Nov 5, 2020 2:52:32 AM> <INFO> <LibraryHelper> <extract_classpath_libraries> <WLSDPLY-12218> <The archive file /shared/wdt-as-msp01-domain3/wlsdeploy.zip contains no classpath libraries to install>
####<Nov 5, 2020 2:52:32 AM> <INFO> <LibraryHelper> <install_domain_scripts> <WLSDPLY-12241> <The model did not specify any domain scripts to install>
####<Nov 5, 2020 2:52:32 AM> <INFO> <Creator> <_set_attribute> <WLSDPLY-12106> <No WLST attribute name for model attribute DomainVersion at model path topology:/>

Issue Log for createDomain version 1.9.6 running WebLogic version 12.2.1.4.0 offline mode:

Total:       WARNING :     0    SEVERE :     0

createDomain.sh completed successfully (exit code = 0)
```

**Comment by CarolynRountree** [comment] 2020-11-05 15:41
There is a method behind this madness. create_placeholder looks up the list of existing servers, and if the current server is not in the list, it creates the server. It adds no attributes, it doesn't deal with the archive file. It is one of the first items to be created after the templates are applied. So the idea would be that a bare bones model might possibly behave the same way in your environment. We have ruled out environment, unless there is some kind of security in play. Would you be able to attach the entire topology section of your model?

**Comment by dborysenko** [comment] 2020-11-05 16:16
@CarolynRountree , Can I share the model privately? Maybe through oracle support case? I do not want to leak something internal to the public.

**Comment by ddsharpe** [comment] 2020-11-05 16:36
@dborysenko do you have access to Slack?  We have private DMs there on the weblogic workspace, as well as channels.

**Comment by dborysenko** [comment] 2020-11-05 17:22
I do. Can you please share link?

**Comment by rjeberhard** [comment] 2020-11-05 17:25
https://weblogic-slack-inviter.herokuapp.com/

**Comment by robertpatrick** [comment] 2021-12-23 18:06
@dborysenko did this issue ever get resolved (i.e., via Slack)?  If not, where are we with the issue and what do we need to do to get this resolved?

**Comment by dborysenko** [comment] 2021-12-23 18:07
Hi @robertpatrick 
As far as I know no, it was not resolved.

**Comment by robertpatrick** [comment] 2022-01-03 22:44
Cannot reproduce and no one else reporting the issue.  Closing for now.

**Closed by robertpatrick** 2022-01-03 22:44 UTC
Labels: help wanted
