### ISSUE TITLE
 ClasspathServletSecureModeEnabled parameter doesn't work for OSB domain

### ISSUE THREAD

**Issue by pwninja** [oracle/weblogic-deploy-tooling#1117] opened 2022-04-14 09:17 UTC
I configured OSB domain using WDT providing:
```
ClasspathServletSecureModeEnabled: false
```
This doesn't work, which I tested both by reproducing issue described in [Doc Id 2777539.1](https://support.oracle.com/epmos/faces/DocumentDisplay?id=2777539.1)
and by logging into AdminServer, connecting using WLST to verify that:
```
wls:/my_domain/serverConfig/> cd ('Servers/AdminServer')
wls:/my_domain/serverConfig/Servers/AdminServer> ls()
(...)
-r--   ClasspathServletDisabled                     false
-r--   ClasspathServletSecureModeEnabled            true
(...)
```
I can confirm that Weblogic properly reacts on modification of `ClasspathServletDisabled` property - this should stay as "false", but for testing purpose I was modifying it just to see if it changes.

I am using WDT 2.1.1 version and OSB 12.2.1.4.0

**Comment by CarolynRountree** [comment] 2022-04-14 19:34
This sounds like an OSB template is overriding the value. We have a fix for this coming up in the next release. You can get a zip of the installer out of the main branch if you wish to try it out.

**Comment by robertpatrick** [comment] 2022-04-15 00:12
@pwninja Please post the typedef file you created in order to provision an OSB domain.  This will help us narrow down the exact templates being applied to confirm that the cause of the problem is one of the templates' final.py file overriding the value.  If that proves to be the case, then Carolyn's advice is correct that we have addressed this issue in the source code and it will be part of the next WDT release.

**Comment by robertpatrick** [comment] 2022-04-15 03:09
@pwninja OK, this has nothing to do with any final.py change and is easily reproduced with a WebLogic Server only domain.

It appears to be an issue that the Oracle PSU team created by changing the default value of the attribute in "online" mode but not in "WLST offline" mode.  Because WLST offline thinks the default is still `false`, it will not add the attribute to config.xml unless the value is set to `true`.  If we use WLST offline to change the value to `false` after the domain is created (and since WLST offline believes that the attribute's default value is false), the attribute is removed from config.xml.  I am not sure that there is anything WDT can reasonably do to work around this WLST bug created by the incomplete PSU change.  

My advice is to file a bug on WLS for making this change, which makes it impossible to disable this attribute without either hand-editing config.xml or running an online config change.  @mriccell @ddsharpe FYI

**Comment by pwninja** [comment] 2022-04-15 07:52
Thank you for swift response!
Should I take any specific action then?

**Comment by robertpatrick** [comment] 2022-04-15 12:40
@pwninja If you need this to work, you should file a Bug against WLST offline with Oracle Support.

**Comment by robertpatrick** [comment] 2023-02-07 13:11
@pwninja This issue is fixed as of the October 2022 PSU so closing this issue.

**Closed by robertpatrick** 2023-02-07 13:11 UTC
Labels: WLST bug
